repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [ python ]
        args: [--no-strict-optional, --ignore-missing-imports]
        stages: [commit]
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        stages: [commit]
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [ python ]
        exclude: '.*/migrations/.*'
        args: [
            '--line-length=110',
            '--multi-line=3',
            '--force-grid-wrap=0',
            '--trailing-comma',
            '--use-parentheses',
            '--ensure-newline-before-comments',
        ]
        stages: [commit]
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        stages: [commit]
